
opsemail = "opsqdev2021@outlook.com"
opspassword = "Quantuvos@123"
URL = "https://platform-dev.quantuvos.com/login"
TEMPURL = "https://temp-mail.org/en/"
clientemail = "qclientprofile@gmail.com"
clientpassword = "1234Test."
coachemail = "qcoachprofile@gmail.com"
coachpassword = "Test1234."
password = "Qwerty@123"
